name: Build
on: [push]
jobs:
  gradle:
    strategy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Execute Gradle build
      run: ./gradlew build --no-daemon
