name: Build
on: [push]
jobs:
  gradle:
    strategy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
        
    - name: Execute Gradle build
      run: ./gradlew build 
    - name: Execute Gradle test
      run: ./gradlew test 
