@startuml

hide empty description
[*] --> NoMap

NoMap --> MapLoaded : loadMap

MapLoaded --> IntersectionSelected : selectIntersection
MapLoaded --> RequestSelected : selectRequest

IntersectionSelected --> MapLoaded : selectIntersection\n(the same)
IntersectionSelected --> RequestSelected : addDelivery
IntersectionSelected --> RequestSelected : selectRequest
IntersectionSelected --> IntersectionSelected : selectIntersection\n(an other one)

RequestSelected --> IntersectionSelected : selectIntersection
RequestSelected --> MapLoaded : removeDelivery
RequestSelected --> RequestSelected : selectRequest\n(an other one)

@enduml